[package]
name = "logdna-agent"
version = "2.1.4"
authors = ["CJP10 <connor.peticca@logdna.com>"]
edition = "2018"

[[bin]]
name = "logdna-agent"
path = "src/main.rs"

[dependencies]
#local
http = { package = "http", path = "../common/http" }
fs = { package = "fs", path = "../common/fs" }
config = { package = "config", path = "../common/config" }
middleware = { package = "middleware", path = "../common/middleware" }
k8s = { package = "k8s", path = "../common/k8s" }

log = "0.4"
env_logger = "0.6"