[workspace]
members = [
    "logdna-agent",
    "logdna-agent-config",
    "logdna-agent-core",
    "logdna-agent-fs",
    "logdna-agent-http",
]

[profile.release]
opt-level = 3
lto = true
debug = true
panic = "abort"