[workspace]
members = [
    "bin",
    "common/config",
    "common/config-macro",
    "common/fs",
    "common/http",
    "common/middleware",
]

[profile.release]
opt-level = 3
debug = true
panic = "abort"