version: 2

jobs:
  build:
    docker:
      - image: circleci/rust:latest
    steps:
      - checkout
      - run:
          name: Install
          command: |
            rustup component add rustfmt
            rustup component add clippy
      - run:
          name: Lint
          command: |
            cargo clippy
      - run:
          name: Build
          command: |
            cargo build