version: 2

jobs:
  build:
    docker:
      - image: circleci/rust:latest
    steps:
      - checkout
      - run:
          name: Install
          command: |
            rustup component add rustfmt
            rustup component add clippy
      - run:
          name: Lint
          command: |
            rustfmt --version
            cargo fmt -- --write-mode=diff
      - run:
          name: Build
          command: |
            cargo build