version: 2.1

jobs:
  check:
    docker:
      - image: rust:latest
    steps:
      - checkout
      - run:
          name: Check
          command: |
            cargo check
  build-tag:
    environment:
      IMAGE_NAME: logdna/logdna-agent-v2
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            echo "${DOCKER_PASS}" | docker login -u "${DOCKER_USER}" --password-stdin
            docker build -t $IMAGE_NAME:stable -t $IMAGE_NAME:latest -t $IMAGE_NAME:$CIRCLE_TAG .
            docker push $IMAGE_NAME:stable $IMAGE_NAME:latest -t $IMAGE_NAME:$CIRCLE_TAG
  build-master:
    environment:
      IMAGE_NAME: logdna/logdna-agent-v2
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            echo "${DOCKER_PASS}" | docker login --username "${DOCKER_USER}" --password-stdin
            docker build -t $IMAGE_NAME:master .
            docker push $IMAGE_NAME:master

workflows:
  version: 2
  check:
    jobs:
      - check
  build-master:
    jobs:
      - build-master:
          filters:
            branches:
              only: master
  build-tag:
    jobs:
      - build-tag:
          filters:
            tags:
              only: /[0-9]+\.[0-9]+\.[0-9]+/
            branches:
              ignore: /.*/