[package]
name = "logdna-agent-http"
version = "0.1.0"
authors = ["CJP10 <connor.peticca@logdna.com>"]
edition = "2018"

[dependencies]
#agent
agent-core = { package = "logdna-agent-core", path = "../logdna-agent-core" }
#io
tokio = "0.1"
#utils
log = "0.4"
crossbeam = "0.7"
uuid = { version = "0.7", features = ["v4"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = "0.4"
quick-error = "1"
either = "1"